# Generated by Django 3.1.7 on 2021-02-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.TextField(max_length=10)),
                ('device_token', models.TextField(max_length=200)),
            ],
        ),
    ]
